// Hidden renderer: synthetic pointer events, fake network and fake clipboard.
const assert=require('node:assert/strict');
const path=require('node:path');
const {mkdirSync,mkdtempSync,writeFileSync}=require('node:fs');
const {pathToFileURL}=require('node:url');
const {app,BrowserWindow,nativeImage}=require('electron');
const root=path.dirname(__dirname);mkdirSync(path.join(root,'work'),{recursive:true});
const dataDir=mkdtempSync(path.join(root,'work','features-ui-'));
app.setPath('userData',path.join(dataDir,'profile'));
let service,server,main,releaseInk,hold=false,textOnly=false,fail=false;
const inkCalls=[],imageCalls=[],usageCalls=[],errors=[];let mixedResult={text:'已知 $x+1$'};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label){for(let n=0;n<220;n++){const value=await fn();if(value)return value;await delay(50);}throw new Error('Timed out: '+label);}
const json=data=>new Response(JSON.stringify(data));
async function run(){
  await app.whenReady();
  const {createApp}=await import(pathToFileURL(path.join(root,'server.js')).href);
  service=await createApp({dataDir,testCredentials:{appId:'test',appKey:'fake'},fetchImpl:async(url,req)=>{
    if(url.includes('/v3/ocr-usage?')) {usageCalls.push(url);return json({ocr_usage:[['image',5],['scs-page',36],['pdf-page',1],['c-docx',4]].map(([usage_type,count])=>({usage_type,count,from_date:'2026-09-22T00:00:00Z'}))});}
    if(url.endsWith('/v3/text')){const bytes=Buffer.from(await req.body.get('file').arrayBuffer());imageCalls.push(bytes);return json(mixedResult);}
    assert.equal(url.endsWith('/v3/strokes'),true);inkCalls.push(JSON.parse(req.body));
    if(hold)await new Promise(r=>{releaseInk=r;});if(fail)return new Response('{}',{status:500});
    return json(textOnly?{text:'文字与 $x$'}:{text:'$x+1$',latex_styled:'x+1',request_id:'test-ink'});
  }});
  server=service.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  main=new BrowserWindow({width:1400,height:1000,show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false,offscreen:true}});
  main.webContents.on('console-message',(...args)=>{const d=args.find(v=>v&&typeof v==='object'&&'message'in v);if(d?.level==='error')errors.push(d.message);});
  await main.loadURL('http://127.0.0.1:'+server.address().port);
  const evaluate=async js=>{try{return await main.webContents.executeJavaScript(js);}catch(e){throw new Error(e.message+'\nRenderer check: '+js);}};
  await until(()=>evaluate('document.querySelector("#mode").textContent.includes("API 已配置")'),'app loaded');
  await evaluate('document.querySelector("#open-ink").click()');
  await until(()=>evaluate('document.querySelector("#ink-dialog").open'),'ink opens');
  assert.equal(await evaluate('document.querySelector("#ink-recognize").disabled'),true);
  assert.equal(await evaluate('document.querySelector("#ink-auto").checked'),false);
  const draw=async(offset=0,cancel=false)=>evaluate(`{
    const c=document.querySelector('#ink-canvas'),r=c.getBoundingClientRect();c.setPointerCapture=()=>{};c.hasPointerCapture=()=>false;
    const event=(type,x,y)=>new PointerEvent(type,{bubbles:true,pointerId:2,pointerType:'pen',button:0,clientX:r.left+x/1200*r.width,clientY:r.top+y/450*r.height});
    c.dispatchEvent(event('pointerdown',100+${offset},100));
    const move=event('pointermove',200+${offset},150);Object.defineProperty(move,'getCoalescedEvents',{value:()=>[event('pointermove',150+${offset},120),move]});c.dispatchEvent(move);
    c.dispatchEvent(event(${JSON.stringify(cancel?'pointercancel':'pointerup')},250+${offset},200));
  }`);
  await draw();await draw(80,true);assert.equal(await evaluate('document.querySelector("#ink-count").textContent'),'1 笔');
  await evaluate('document.querySelector("#ink-recognize").click();document.querySelector("#ink-recognize").click()');
  await until(()=>evaluate('document.querySelector("#ink-source").value==="x+1" && !document.querySelector("#ink-copy").disabled'),'ink result');
  assert.equal(inkCalls.length,1);assert.equal(inkCalls[0].strokes.strokes.x[0].length,4);
  await evaluate('Object.defineProperty(navigator.clipboard,"writeText",{configurable:true,value:async value=>{window.testCopied=value;}});document.querySelector("#ink-copy").click()');
  await until(()=>evaluate('window.testCopied==="x+1"'),'ink copy');
  await evaluate('document.querySelector("#ink-recognize").click()');await delay(80);assert.equal(inkCalls.length,1);
  await until(()=>evaluate('document.querySelector("#ink-preview mjx-container") && !document.querySelector("#ink-recognize").disabled'),'math preview');await delay(250);
  writeFileSync(path.join(dataDir,'ink-preview.png'),(await main.webContents.capturePage()).toPNG());
  await evaluate('document.querySelector("#ink-save").click()');await until(()=>evaluate('!document.querySelector("#ink-dialog").open && document.querySelector("#title").value.startsWith("手写公式")'),'ink history');
  await evaluate('document.querySelector("#open-ink").click()');await until(()=>evaluate('document.querySelector("#ink-dialog").open'),'reopen');
  assert.equal(await evaluate('document.querySelector("#ink-count").textContent'),'1 笔');
  await draw(130);await evaluate('document.querySelector("#ink-undo").click()');assert.equal(await evaluate('document.querySelector("#ink-count").textContent'),'1 笔');
  await evaluate('document.querySelector("#ink-clear").click()');assert.equal(await evaluate('document.querySelector("#ink-recognize").disabled'),true);
  textOnly=true;await draw(60);await evaluate('document.querySelector("#ink-recognize").click()');await until(()=>evaluate('document.querySelector("#ink-source").value.includes("文字")'),'fallback');
  assert.equal(await evaluate('document.querySelector("#ink-copy").textContent'),'复制识别文本');
  hold=true;textOnly=false;await draw(190);await evaluate('document.querySelector("#ink-recognize").click()');await until(()=>releaseInk,'delayed call');
  await draw(240);releaseInk();hold=false;await until(()=>evaluate('!document.querySelector("#ink-recognize").disabled'),'delayed result');assert.equal(await evaluate('document.querySelector("#ink-source").value'),'');
  fail=true;await evaluate('document.querySelector("#ink-auto").click()');await until(()=>evaluate('document.querySelector("#ink-status").textContent.includes("自动识别已暂停")'),'auto failure');
  assert.equal(await evaluate('document.querySelector("#ink-auto").checked'),false);
  const submitted=inkCalls.length;await delay(1600);assert.equal(inkCalls.length,submitted);
  await evaluate('document.querySelector("#ink-auto").click();document.querySelector("#ink-dialog .close").click()');await delay(1600);assert.equal(inkCalls.length,submitted);
  await new Promise(resolve=>{main.webContents.once('did-finish-load',resolve);main.reload();});await until(()=>evaluate('document.querySelector("#mode").textContent.includes("API 已配置") && document.querySelector("#title").value.startsWith("手写公式")'),'reload');
  await evaluate('document.querySelector("#open-ink").click()');await until(()=>evaluate('document.querySelector("#ink-dialog").open'),'restored draft');
  assert.equal(await evaluate('document.querySelector("#ink-count").textContent'),'3 笔');
  fail=false;textOnly=false;
  await evaluate('document.querySelector("#ink-clear").click()');
  const addText=async(value,x=20,y=120)=>{
    await evaluate(`{
      document.querySelector('#ink-text-tool').click();
      const c=document.querySelector('#ink-canvas'),r=c.getBoundingClientRect();
      c.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:5,pointerType:'mouse',button:0,clientX:r.left+${x}/1200*r.width,clientY:r.top+${y}/450*r.height}));
      const input=document.querySelector('#ink-text-layer').lastElementChild.querySelector('input');input.value=${JSON.stringify(value)};input.dispatchEvent(new Event('input',{bubbles:true}));input.blur();
    }`);
  };
  await addText('已知');await evaluate('document.querySelector("#ink-pen-tool").click()');await draw(200);
  assert.match(await evaluate('document.querySelector("#ink-count").textContent'),/1 笔.*1 个文字框/);
  await evaluate('document.querySelector("#ink-recognize").click()');
  await until(()=>evaluate('document.querySelector("#ink-source").value.includes("已知 $x+1$") && !document.querySelector("#ink-recognize").disabled'),'mixed text result');
  const mixedCalls=inkCalls.length;assert.equal(imageCalls.length,1);mixedResult={text:"求解 $x+1$"};
  await evaluate(`{const input=document.querySelector('.ink-text input');input.focus();input.value='求解';input.dispatchEvent(new Event('input',{bubbles:true}));input.blur();document.querySelector('#ink-recognize').click();}`);
  await until(()=>evaluate('document.querySelector("#ink-source").value.includes("求解 $x+1$") && !document.querySelector("#ink-recognize").disabled'),'text edit submits updated complete layout');
  assert.equal(inkCalls.length,mixedCalls);assert.equal(imageCalls.length,2);
  await evaluate(`{
    const c=document.querySelector('#ink-canvas'),r=c.getBoundingClientRect(),grip=document.querySelector('.ink-text-grip');grip.setPointerCapture=()=>{};
    const event=(type,x,y)=>new PointerEvent(type,{bubbles:true,pointerId:7,pointerType:'mouse',button:0,clientX:r.left+x/1200*r.width,clientY:r.top+y/450*r.height});
    grip.dispatchEvent(event('pointerdown',25,110));document.dispatchEvent(event('pointermove',65,135));document.dispatchEvent(event('pointerup',65,135));
  }`);
  const moved=await evaluate('JSON.parse(localStorage.getItem("mathsnip-ink-draft")).texts[0]');
  assert.ok(Math.abs(moved.x-60)<1);assert.ok(Math.abs(moved.y-145)<1);
  await evaluate('document.querySelector(".ink-text-delete").click()');assert.equal(await evaluate('document.querySelectorAll(".ink-text").length'),0);
  await evaluate('document.querySelector("#ink-undo").click()');assert.equal(await evaluate('document.querySelector(".ink-text input").value'),'求解');
  await evaluate('document.querySelector("#ink-recognize").click()');await until(()=>evaluate('!document.querySelector("#ink-save").disabled && !!document.querySelector("#ink-preview mjx-container")'),'mixed preview');
  assert.equal(inkCalls.length,mixedCalls);assert.equal(imageCalls.length,3);await delay(250);
  writeFileSync(path.join(dataDir,'ink-text-preview.png'),(await main.webContents.capturePage()).toPNG());
  await evaluate('document.querySelector("#ink-save").click()');await until(()=>evaluate('!document.querySelector("#ink-dialog").open && document.querySelector("#editor").value.includes("求解")'),'save mixed history');
  const allItems=await Promise.all((await service.store.list()).map(i=>service.store.get(i.id)));
  assert.ok(allItems.some(i=>i.inkTexts?.[0]?.text==='求解'&&Math.abs(i.inkTexts[0].x-60)<1));
  await evaluate('document.querySelector("#open-ink").click()');await until(()=>evaluate('document.querySelector("#ink-dialog").open'),'typed only board');
  await evaluate('document.querySelector("#ink-clear").click()');await addText('仅输入汉字');
  await evaluate('document.querySelector("#ink-recognize").click()');await until(()=>evaluate('document.querySelector("#ink-source").value==="仅输入汉字" && !document.querySelector("#ink-recognize").disabled'),'typed only local');
  assert.equal(inkCalls.length,mixedCalls);
  await evaluate('document.querySelector("#ink-dialog .close").click()');
  await new Promise(resolve=>{main.webContents.once('did-finish-load',resolve);main.reload();});await until(()=>evaluate('document.querySelector("#mode").textContent.includes("API 已配置")'),'mixed reload');
  await evaluate('document.querySelector("#open-ink").click()');await until(()=>evaluate('document.querySelector("#ink-dialog").open'),'text draft reload');
  assert.equal(await evaluate('document.querySelector(".ink-text input").value'),'仅输入汉字');
  await evaluate('document.querySelector("#ink-clear").click();document.querySelector("#ink-pen-tool").click()');
  await evaluate(`{
    const c=document.querySelector('#ink-canvas'),r=c.getBoundingClientRect();c.setPointerCapture=()=>{};c.hasPointerCapture=()=>false;
    const points=[[100,100],[100,130],[102,145],[110,155],[130,160],[150,155],[158,145],[160,130],[160,100]];
    points.forEach(([x,y],i)=>c.dispatchEvent(new PointerEvent(i===0?'pointerdown':i===points.length-1?'pointerup':'pointermove',{bubbles:true,pointerId:2,pointerType:'pen',button:0,clientX:r.left+x/1200*r.width,clientY:r.top+y/450*r.height})));
  }`);
  await addText('真实',165,150);
  await evaluate(`{const size=document.querySelector('.ink-text-size');size.focus();size.value='18';size.dispatchEvent(new Event('change',{bubbles:true}));size.blur();}`);
  assert.equal(await evaluate('JSON.parse(localStorage.getItem("mathsnip-ink-draft")).texts[0].fontSize'),18);
  mixedResult={latex_styled:String.raw`U_{\text{真实}}`,text:String.raw`$U_{\text{真实}}$`};
  await evaluate('document.querySelector("#ink-recognize").click()');
  await until(()=>evaluate('document.querySelector("#ink-source").value.includes("真实") && !document.querySelector("#ink-recognize").disabled'),'complete U layout');
  assert.equal(await evaluate('document.querySelector("#ink-source").value'),mixedResult.latex_styled);
  const uImage=imageCalls.at(-1),smallImage=nativeImage.createFromBuffer(uImage);
  assert.equal(smallImage.isEmpty(),false);const smallSize=smallImage.getSize();
  const pixels=smallImage.toBitmap();assert.deepEqual([...pixels.subarray(0,4)],[255,255,255,255]);
  writeFileSync(path.join(dataDir,'u-typed-text-upload.png'),uImage);
  const imageCount=imageCalls.length;await evaluate('document.querySelector("#ink-recognize").click()');await delay(80);assert.equal(imageCalls.length,imageCount);
  await evaluate(`{const size=document.querySelector('.ink-text-size');size.value='48';size.dispatchEvent(new Event('change',{bubbles:true}));}`);
  await evaluate('document.querySelector("#ink-recognize").click()');await until(()=>imageCalls.length===imageCount+1,'size change invalidates layout');
  await until(()=>evaluate('!document.querySelector("#ink-recognize").disabled'),'resized result');
  const bigSize=nativeImage.createFromBuffer(imageCalls.at(-1)).getSize();assert.ok(bigSize.width>smallSize.width&&bigSize.height>smallSize.height);
  await evaluate('document.querySelector("#ink-undo").click()');assert.equal(await evaluate('document.querySelector(".ink-text-size").value'),'18');
  await evaluate('document.querySelector("#ink-recognize").click()');await until(()=>evaluate('!document.querySelector("#ink-save").disabled'),'undo restores small layout cache');assert.equal(imageCalls.length,imageCount+1);
  await evaluate('document.querySelector(".ink-text-content").focus()');await delay(250);
  writeFileSync(path.join(dataDir,'ink-size-preview.png'),(await main.webContents.capturePage()).toPNG());
  await evaluate('document.querySelector("#ink-save").click()');await until(()=>evaluate('!document.querySelector("#ink-dialog").open'),'save size');
  const savedItems=await Promise.all((await service.store.list()).map(i=>service.store.get(i.id)));assert.ok(savedItems.some(i=>i.inkTexts?.[0]?.fontSize===18&&i.inkTexts[0].text==='真实'&&i.inkMode==='layout-image'));
  await new Promise(resolve=>{main.webContents.once('did-finish-load',resolve);main.reload();});await until(()=>evaluate('document.querySelector("#mode").textContent.includes("API 已配置")'),'size reload');
  await evaluate('document.querySelector("#open-ink").click()');await until(()=>evaluate('document.querySelector("#ink-dialog").open'),'restore size');assert.equal(await evaluate('document.querySelector(".ink-text-size").value'),'18');
  await evaluate('document.querySelector("#ink-dialog .close").click();document.querySelector("#open-usage").click()');
  await until(()=>evaluate('!document.querySelector("#usage-content").hidden'),'usage loads');
  assert.match(await evaluate('document.querySelector("#usage-summary").textContent'),/Files 文档36页/);
  assert.match(await evaluate('document.querySelector("#usage-types").textContent'),/c-docx.*4.*未估价/);
  assert.match(await evaluate('document.querySelector("#usage-cost").textContent'),/0.0690/);
  await evaluate('document.querySelector("#usage-from").value="2026-09-01";document.querySelector("#usage-to").value="2026-09-23";document.querySelector("#usage-load").click()');
  await until(()=>usageCalls.length===2,'usage refresh');await until(()=>evaluate('!document.querySelector("#usage-load").disabled'),'refresh settles');
  assert.equal(new URL(usageCalls[1]).searchParams.get('to_date'),'2026-09-24T00:00:00.000Z');
  assert.equal(await evaluate('document.querySelector("#usage-dialog").open'),true);await delay(250);
  writeFileSync(path.join(dataDir,'usage-preview.png'),(await main.webContents.capturePage()).toPNG());
  assert.equal(main.isVisible(),false);assert.equal(errors.every(message=>/Failed to load resource.*500/.test(message)),true,JSON.stringify(errors));
  console.log(JSON.stringify({result:'PASS',dataDir,inkRequests:inkCalls.length,imageRequests:imageCalls.length,usageQueries:usageCalls.length,checks:['empty ink','raw coalesced samples','pointer cancel','dedup','fake clipboard copy','save history','undo/clear','text fallback','stale response','auto error pause','close cancels automatic calls','draft survives reload','typed Chinese and ink composition','text-only recognition without remote call','whole layout image preserves position and size','font size change and undo','size persists in history and draft','drag/delete/undo text','mixed history and text draft reload','official usage tables and estimates','UTC inclusive range','no visible windows']}));
}
run().then(async()=>{await service.pdf.close();await service.word.close();server.closeAllConnections();server.close();app.exit(0);}).catch(async e=>{console.error(e.stack);await service?.pdf.close();await service?.word.close();server?.closeAllConnections();server?.close();app.exit(1);});
